// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240401075049_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("85dd5acf-2a71-4a99-b6ee-bf07f0e0728b"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 2, 1, 10, 50, 48, 511, DateTimeKind.Local).AddTicks(7109),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("6e0d750a-e4d0-4562-a8b1-bfdfe7f43493"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2024, 3, 1, 10, 50, 48, 511, DateTimeKind.Local).AddTicks(7127),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("17fb418b-35e7-472e-b667-8395dd200e6b"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2024, 5, 1, 10, 50, 48, 511, DateTimeKind.Local).AddTicks(7130),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("bd1c6c2b-eb22-4b60-add8-12dfa7a25005"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 6, 1, 10, 50, 48, 511, DateTimeKind.Local).AddTicks(7132),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("333fb113-8b22-4a24-9c5b-5abd50d11dfb"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 7, 1, 10, 50, 48, 511, DateTimeKind.Local).AddTicks(7135),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("256716d7-4e4c-4e9d-a4df-05df41e4b570"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 8, 1, 10, 50, 48, 511, DateTimeKind.Local).AddTicks(7147),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("4546613f-14a6-47e2-8993-06fd07047737"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 9, 1, 10, 50, 48, 511, DateTimeKind.Local).AddTicks(7149),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("2467dc18-56ff-427a-b493-0762a25024fe"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 10, 1, 10, 50, 48, 511, DateTimeKind.Local).AddTicks(7152),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("d66f9e9a-97d8-4bcc-9272-4a4728dbfbe4"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2024, 11, 1, 10, 50, 48, 511, DateTimeKind.Local).AddTicks(7154),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("9788cb9a-75e0-4eaf-ab57-b9eeceef758b"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2024, 12, 1, 10, 50, 48, 511, DateTimeKind.Local).AddTicks(7157),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
